version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "127.0.0.1:6333:6333"
      - "127.0.0.1:6334:6334"
    environment:
      - QDRANT__TELEMETRY_DISABLED=true
    volumes:
      # To save C:\ drive space, this bind mount saves data directly to a folder 
      # next to this docker-compose file. You can also change './qdrant_data' 
      # to an absolute path on another drive, for example: 'D:/my_qdrant_data'
      - ./qdrant_data:/qdrant/storage
